### PR TITLE
Multiple fix

### LINKED ISSUE #31: Re-starting a discovery causes a crash
`java.lang.IllegalStateException: Discovery is already in progress - did you call discoverDevices() multiple times?`

`onCompletion` is never called from the demo.

Actually the stop button in the demo is enabled at the wrong time, but fixing that, hitting stop causes a hang, fixing that, causes a crash when it's restarted.

### PR DESCRIPTION
**Pull request by sproctor**
The protection against multiple concurrent usages was broken to never allow restarting. This change is pretty significant, but also simple. `LighthouseState` is no longer a member variable, instead a new state is created on each call to `LighthouseClient.discoverDevices()`. `shouldPersist` is no longer possible to implement. If that feature is required, an existing list could be passed to `discoverDevices`.

I removed `DiscoveryManager`. It didn't actually manage anything anymore. The two helper functions from there made more sense as part of `RealLighthouseClient`.

Fixes #31

### CODE REVIEW

**Comment by sproctor** [comment]
One last thing to note, `discoverDevices` now runs on the current coroutine context and the proper context should be set by the consumer.

**Comment by ivanempire** [comment]
Two quick notes:
1) Is the idea to have `.flowOn()` at the consumer level?
2) Won't the removal of the mutex cause an issue where the second call to `discoverDevices()` throws an error up the Flow?

**Comment by ivanempire** [comment]
Closing for now since we're both async on this work - feel free to reopen :)

**Comment by sproctor** [comment]
1. Deciding which dispatcher to use should be left to the user.

2. A new `LighthouseState` is created on each `discoverDevices()` call, so it avoids the issues with re-use. I don't remember if I tried concurrent searches. If you're interested in this work I can test it and make any relevant fixes.

You don't seem keen on merging my stuff, so unless you tell me otherwise, I'll just leave stuff on my own branch. It'll save me the work of trying to make things mostly mergeable (although, I did make a lot of my merges dependent on previous ones because I didn't have the time to break them up completely).

**Comment by ivanempire** [comment]
Nah I'm cool with it, I just want smaller commits/also been taking a break. You're all good, I just also don't have the best environment for testing on desktop - I swear I'll get to it xD

**Pull request closed without merging**
