### PR TITLE
Use string instead of UUID for uuid in USN

### PR DESCRIPTION
**Pull request by sproctor**
Devices supporting UPnP 1.0 are not guaranteed to give a valid UUID

This fixes issue #4

### CODE REVIEW

**Comment by ivanempire** [comment]
Not a fan of this (the spec, not the code), but looks good! Some linting errors, but good to submit once that passes - thanks! 🚀

**Comment by ivanempire** [comment]
Wait, actually, I don't think this is the best way. In your example: `uuid:Upnp-BasicDevice-1_0-B8A44F26437D::upnp:rootdevice` - this is fine, I guess the full string is OK, but other devices return something like `uuid:3f8744cd-30bf-4fc9-8a42-bad80ae660c1::urn:schemas-upnp-org:service:Dimming:1`, and the UUID should not be the full string, it should just be the relevant substring. In fact, an easier solution would just to return the full string into the `uuid: String` field if `rawValue.parseUuid()` doesn't find a match.

**Comment by ivanempire** [comment]
https://github.com/ivanempire/lighthouse/pull/9/files#diff-b11e582af33d03ce45521999787bc9d62f5854bb7dff8b0b5f0176c65e615748L114
Instead of returning that, the original value can be returned

**Comment by sproctor** [comment]
I'm not sure what you mean. My change doesn't return the full string. The UUID is the second segment of the USN, which is what is returned. https://github.com/ivanempire/lighthouse/pull/9/files#diff-b11e582af33d03ce45521999787bc9d62f5854bb7dff8b0b5f0176c65e615748R27

"uuid:stuff:morestuff" would result in the UUID being "stuff". A USN of "stuff" would result in the UUID being `NOT_AVAILABLE_UUID`. The USN is required to start with "uuid:", so I think that is appropriate.

**Comment by ivanempire** [comment]
Ah yeah I see it now, sorry, was running around when I looked this over and just saw the REGEX constant missing. Thanks for this - can you fix the linting issue and then I'll merge it:
```
/home/runner/work/lighthouse/lighthouse/lighthouse/src/main/java/com/ivanempire/lighthouse/models/packets/UniqueServiceName.kt:12:28 Missing spacing before "{" (curly-spacing)
/home/runner/work/lighthouse/lighthouse/lighthouse/src/main/java/com/ivanempire/lighthouse/models/packets/UniqueServiceName.kt:32:50 Unexpected spacing before "," (comma-spacing)
```

**Comment by sproctor** [comment]
I reworked the USN parser to to avoid any possibility of an array out of bounds error from the splits. It's slightly more strict in certain ways. It expects "device" or "service" to be after a "::" and the UUID isn't recognized if it doesn't start with "uuid:".

**Comment by sproctor** [comment]
Unrelated, why is the boot id a member of the USN? They don't appear to be related in the spec nor in usage within Lighthouse. Is it a relic of some previous design? It doesn't appear to ever be read or is there something I'm missing?

**Comment by ivanempire** [comment]
I tied it together because I couldn't find out in the spec if a bootId is unique for a root device only, or if every single embedded device and service has its own bootId (for example, some embedded device in a smart TV or something rebooting after an update, but the TV not needing to reboot itself). I can probably remove it in a follow-up PR if I don't find anything that confirms this one way or another.

**Pull request merged**
