### PR TITLE
Add a simple demo and support AXIS cameras

### PR DESCRIPTION
**Pull request by sproctor**
I don't think this is going to work for me, but I figured I'd send this over.

Without this PR, this library doesn't build due to missing gradle variables. I'd recommend using https://vanniktech.github.io/gradle-maven-publish-plugin/ as it simplifies publishing.

### CODE REVIEW

**Comment by ivanempire** [comment]
Hey! So I know there's an issue with the Gradle variables, but that should only happen if you're trying to include the project via the Gradle `include` directive as you did. Is that the issue or it just flat out doesn't work when pulling from Maven?

**Comment by sproctor** [comment]
The issue with the variables only happens when trying to build locally, but it's a bit of a bummer for potential contributors.

I'm looking for a library to use on Android and JVM targets. Would you be willing to accept changes to make this multiplatform?

**Comment by sproctor** [comment]
Sorry, this PR is getting out of hand. I can put individual pieces into separate pull requests if you'd like.

I'm learning SSDP as I make changes. This is almost working for me now, so I'm going to add multiplatform support over the next few days/weeks. If you aren't interested in these changes, feel free to close this PR. I didn't intend to work so much on this, so I didn't make proper branches.

**Comment by ivanempire** [comment]
Nah this is great - I was going to ask for a split, but this is awesome. I'll address questions/concerns here, and in the PR I just opened. Things to note:

1. Thanks for pointing out the Gradle library - I put that on my list of things to do, I did catch the issue rather late in the game. I put your fix in with a `TODO` note to unblock everyone.
2. I cherrypicked some of your fixes over too - specifically (1), the M-SEARCH new line fix, and your flow optimizations. If you want to open your own PR - that's fine too, I made sure mine had your name on it + would give you a callout in the Changelog.
3. What changes do you have in mind for the multiplatform work?

Thank a bunch for this! I'll address the UPnP v1 bug in a second too. 👍

**Comment by ivanempire** [comment]
Oh yeah, forgot to address demo module. I go back and forth on this only because I have an external app that is extremely barebones that I use for testing, however it is a good idea. If you want to open up a PR just for the demo app that'll be awesome.

**Pull request closed without merging**
